server:
  port: 8001
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/jwt?serverTimezone=GMT
    username: root
    password: 145792

mybatis:
  mapper-locations: classpath:com/yjiewei/mapper/*.xml
  type-aliases-package: com.yjiewei.entity

logging:
  level:
    com.yjiewei.dao: debug  # 不知道这里对不对
